liip_imagine:
    driver: "gd"
    filter_sets:
        test:
            jpeg_quality: 85
            filters:
              thumbnail: { size: [250, 250], mode: outbound}
        bo_list:
            jpeg_quality: 85
            filters:
              thumbnail: { size: [250, 150], mode: outbound}   
        front_autopromo:
            jpeg_quality: 100
            filters:
              thumbnail: { size: [1920, 850], mode: outbound}   
        mini_appart:
            jpeg_quality: 100
            filters:
              thumbnail: { size: [150, 100], mode: outbound}         
        front_list:
            jpeg_quality: 100
            filters:
              thumbnail: { size: [380, 250], mode: outbound}         
        front_list_appart:
            jpeg_quality: 100
            filters:
              thumbnail: { size: [260, 300], mode: outbound}         
        front_list_appart_big:
            jpeg_quality: 100
            filters:
              thumbnail: { size: [524, 640], mode: outbound}         