<?php

namespace App\Form;

use App\Entity\Edl;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;


class EdlFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder

            ->add('entree_sonette_interphone', HiddenType::class)
            ->add('entree_sonette_interphone_com')
            ->add('entree_porte_serrurerie', HiddenType::class)
            ->add('entree_porte_serrurerie_com')
            ->add('entree_plafond', HiddenType::class)
            ->add('entree_plafond_com')
            ->add('entree_revetements_muraux', HiddenType::class)
            ->add('entree_revetements_muraux_com')
            ->add('entree_plinthes', HiddenType::class)
            ->add('entree_plinthes_com')
            ->add('entree_sol', HiddenType::class)
            ->add('entree_sol_com')
            ->add('entree_luminaire', HiddenType::class)
            ->add('entree_luminaire_com')
            ->add('entree_interupt_prise', HiddenType::class)
            ->add('entree_interupt_prise_com')
            ->add('entree_placard', HiddenType::class)
            ->add('entree_placard_com')
            ->add('entree_fenetre', HiddenType::class)
            ->add('entree_fenetre_com')
            ->add('entree_volet', HiddenType::class)
            ->add('entree_volet_com')
            ->add('sdb_porte_serrurerie', HiddenType::class)
            ->add('sdb_porte_serrurerie_com')
            ->add('sdb_plafond', HiddenType::class)
            ->add('sdb_plafond_com')
            ->add('sdb_revetements_muraux', HiddenType::class)
            ->add('sdb_revetements_muraux_com')
            ->add('sdb_plinthes', HiddenType::class)
            ->add('sdb_plinthes_com')
            ->add('sdb_sol', HiddenType::class)
            ->add('sdb_sol_com')
            ->add('sdb_luminaire', HiddenType::class)
            ->add('sdb_luminaire_com')
            ->add('sdb_interupt_prise', HiddenType::class)
            ->add('sdb_interupt_prise_com')
            ->add('sdb_radiateur', HiddenType::class)
            ->add('sdb_radiateur_com')
            ->add('sdb_placard', HiddenType::class)
            ->add('sdb_placard_com')
            ->add('sdb_fenetre', HiddenType::class)
            ->add('sdb_fenetre_com')
            ->add('sdb_volet', HiddenType::class)
            ->add('sdb_volet_com')
            ->add('sdb_lavabo', HiddenType::class)
            ->add('sdb_lavabo_com')
            ->add('sdb_robinetterie_lavabo', HiddenType::class)
            ->add('sdb_robinetterie_lavabo_com')
            ->add('sdb_douche', HiddenType::class)
            ->add('sdb_douche_com')
            ->add('sdb_robinetterie_douche', HiddenType::class)
            ->add('sdb_robinetterie_douche_com')
            ->add('sdb_paroi_douche', HiddenType::class)
            ->add('sdb_paroi_douche_com')
            ->add('sdb_baignoire', HiddenType::class)
            ->add('sdb_baignoire_com')
            ->add('sdb_robinetterie_baignoire', HiddenType::class)
            ->add('sdb_robinetterie_baignoire_com')
            ->add('sdb_faience', HiddenType::class)
            ->add('sdb_faience_com')
            ->add('sdb_joints', HiddenType::class)
            ->add('sdb_joints_com')
            ->add('wc_porte_serrurerie', HiddenType::class)
            ->add('wc_porte_serrurerie_com')
            ->add('wc_plafond', HiddenType::class)
            ->add('wc_plafond_com')
            ->add('wc_revetement_muraux', HiddenType::class)
            ->add('wc_revetement_muraux_com')
            ->add('wc_plinthes', HiddenType::class)
            ->add('wc_plinthes_com')
            ->add('wc_sol', HiddenType::class)
            ->add('wc_sol_com')
            ->add('wc_luminaire', HiddenType::class)
            ->add('wc_luminaire_com')
            ->add('wc_interupt_prise', HiddenType::class)
            ->add('wc_interupt_prise_com')
            ->add('wc_radiateur', HiddenType::class)
            ->add('wc_radiateur_com')
            ->add('wc_cuvette_mecanisme', HiddenType::class)
            ->add('wc_cuvette_mecanisme_com')
            ->add('wc_abattant', HiddenType::class)
            ->add('wc_abattant_com')
            ->add('wc_fenetre', HiddenType::class)
            ->add('wc_fenetre_com')
            ->add('wc_volet', HiddenType::class)
            ->add('wc_volet_com')
            ->add('wc_faiences', HiddenType::class)
            ->add('wc_faiences_com')
            ->add('wc_joints', HiddenType::class)
            ->add('ch1_porte_serrurerie', HiddenType::class)
            ->add('ch1_porte_serrurerie_com')
            ->add('ch1_plafond', HiddenType::class)
            ->add('ch1_plafond_com')
            ->add('ch1_revetements_muraux', HiddenType::class)
            ->add('ch1_revetements_muraux_com')
            ->add('ch1_plinthes', HiddenType::class)
            ->add('ch1_plinthes_com')
            ->add('ch1_sol', HiddenType::class)
            ->add('ch1_sol_com')
            ->add('ch1_luminaire', HiddenType::class)
            ->add('ch1_luminaire_com')
            ->add('ch1_interupt_prise', HiddenType::class)
            ->add('ch1_interupt_prise_com')
            ->add('ch1_radiateur', HiddenType::class)
            ->add('ch1_radiateur_com')
            ->add('ch1_placard', HiddenType::class)
            ->add('ch1_placard_com')
            ->add('ch1_fenetre', HiddenType::class)
            ->add('ch1_fenetre_com')
            ->add('ch1_volet', HiddenType::class)
            ->add('ch1_volet_com')
            ->add('ch2_porte_serrurerie', HiddenType::class)
            ->add('ch2_porte_serrurerie_com')
            ->add('ch2_plafond', HiddenType::class)
            ->add('ch2_plafond_com')
            ->add('ch2_revetements_muraux', HiddenType::class)
            ->add('ch2_revetements_muraux_com')
            ->add('ch2_plinthes', HiddenType::class)
            ->add('ch2_plinthes_com')
            ->add('ch2_sol', HiddenType::class)
            ->add('ch2_sol_com')
            ->add('ch2_luminaire', HiddenType::class)
            ->add('ch2_luminaire_com')
            ->add('ch2_interupt_prise', HiddenType::class)
            ->add('ch2_interupt_prise_com')
            ->add('ch2_radiateur', HiddenType::class)
            ->add('ch2_radiateur_com')
            ->add('ch2_placard', HiddenType::class)
            ->add('ch2_placard_com')
            ->add('ch2_fenetre', HiddenType::class)
            ->add('ch2_volet', HiddenType::class)
            ->add('ch2_volet_com')
            ->add('ch3_porte_serrurerie', HiddenType::class)
            ->add('ch3_porte_serrurerie_com')
            ->add('ch3_plafond', HiddenType::class)
            ->add('ch3_plafond_com')
            ->add('ch3_revetements_muraux', HiddenType::class)
            ->add('ch3_revetements_muraux_com')
            ->add('ch3_plinthes', HiddenType::class)
            ->add('ch3_plinthes_com')
            ->add('ch3_sol', HiddenType::class)
            ->add('ch3_sol_com')
            ->add('ch3_luminaire', HiddenType::class)
            ->add('ch3_luminaire_com')
            ->add('ch3_interupt_prise', HiddenType::class)
            ->add('ch3_interupt_prise_com')
            ->add('ch3_radiateur', HiddenType::class)
            ->add('ch3_radiateur_com')
            ->add('ch3_placard', HiddenType::class)
            ->add('ch3_placard_com')
            ->add('ch3_fenetre', HiddenType::class)
            ->add('ch3_fenetre_com')
            ->add('ch3_volet', HiddenType::class)
            ->add('ch3_volet_com')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Edl::class,
        ]);
    }
}
